name: Auto-assign Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  add_self_as_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assign_reviewers.yml"
